telegram:
  api_id: 26330968
  api_hash: gAAAAABpU7LIzjF794Q3rd2riBZdY02LzKPLSzmU1BGs3h6iQYn61Q3EID9ANyIq9cKEik52XcvLOHhbroCe4hzmwKQSLabt0Zzf5HKEFW4_0wxpRyWWVIOhl0ksKKmxdBCn0EDHrmTU
  session_name: "iranhrs_monitor"

  channels:
    - irna_1313
    - ilnair
    - Tasnimnews
    - farsna
    - mizanplus
    - Rokna_news
    - mehrnews

rss:
  feeds:
    - https://www.tasnimnews.ir/fa/rss/feed/0/0/8/1/TopStories
    - https://www.tabnak.ir/fa/rss/1
    - https://www.isna.ir/rss
    - https://mizanonline.ir/fa/rss/allnews

websites:
  - https://www.tasnimnews.ir/
  - https://entekhab.ir/fa/
  - https://mizanonline.ir/fa/
  - https://www.tabnak.ir/
  - https://www.irna.ir/
  - https://www.ilna.ir/
  - https://www.isna.ir/

keywords:
  - اعدام
  - خطر اعدام
  - اجرای حکم
  - حکم اعدام
  - انتقال به انفرادی
  - سلول انفرادی
  - زندان
  - زندانی
  - زندانی سیاسی
  - بازداشت
  - بازداشتی
  - قزلحصار
  - اوین
  - فشافویه
  - رجایی شهر
  - زندان مرکزی
  - محاربه
  - بغی
  - دادگاه انقلاب
  - دیوان عالی
  - اعتراضات

database:
  path: "data/news.db"
